export const FETCH_GBET_SUMMARY_PENDING = 'FETCH_GBET_SUMMARY_PENDING';
export const FETCH_GBET_SUMMARY_FULFILLED = 'FETCH_GBET_SUMMARY_FULFILLED';
export const FETCH_GBET_SUMMARY_REJECTED = 'FETCH_GBET_SUMMARY_REJECTED';

export const FETCH_GBET_TRANSFER_PENDING = 'FETCH_GBET_TRANSFER_PENDING';
export const FETCH_GBET_TRANSFER_FULFILLED = 'FETCH_GBET_TRANSFER_FULFILLED';
export const FETCH_GBET_TRANSFER_REJECTED = 'FETCH_GBET_TRANSFER_REJECTED';

export const FETCH_GBET_HOLDERS_PENDING = 'FETCH_GBET_HOLDERS_PENDING';
export const FETCH_GBET_HOLDERS_FULFILLED = 'FETCH_GBET_HOLDERS_FULFILLED';
export const FETCH_GBET_HOLDERS_REJECTED = 'FETCH_GBET_HOLDERS_REJECTED';
